# ASP.NET Core CI/CD Pipeline for self-hosted agent
trigger:
- main

pool:
  name: Default

variables:
  buildConfiguration: 'Release'

steps:
# Step 1: Restore NuGet packages
- script: dotnet restore
  displayName: 'Restore packages'

# Step 2: Build project
- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'Build project - $(buildConfiguration)'

# Step 3: Run tests
- script: dotnet test --configuration $(buildConfiguration) --no-build --verbosity normal
  displayName: 'Run tests'

# Step 4: Publish app
- script: dotnet publish --configuration $(buildConfiguration) --output "$(Build.ArtifactStagingDirectory)"
  displayName: 'Publish project'

# Step 5: Zip the published files
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'Zip published files'

# Step 6: Publish the zip artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish artifact as zip'
